from __future__ import annotations

import uuid
from vantawave.db.init import initialize_database
from vantawave.db.repositories import (
    DriftRepository,
    EvaluationRepository,
    IncidentRepository,
    ModelSnapshotRepository,
    SensorSessionRepository,
    TargetRepository,
)
from vantawave.db.serialization import orm_to_dict
from vantawave.db.session import create_session_factory, session_scope

def main():
    engine = initialize_database()
    factory = create_session_factory(engine)

    target_id = uuid.uuid4().hex[:12]
    session_id = uuid.uuid4().hex[:12]

    with session_scope(factory) as db:
        target = TargetRepository(db).upsert({
            "target_id": target_id,
            "name": "DB Demo Lab AP",
            "ssid": "VantaWave-Lab",
            "bssid": "02:11:22:33:44:55",
            "authorized": True,
            "owner_confirmation": "Authorized database demonstration target.",
            "notes": "Generated by scripts/db_demo.py",
        })
        sensor_session = SensorSessionRepository(db).upsert({
            "session_id": session_id,
            "target_id": target_id,
            "source": "db-demo",
            "mode": "passive",
            "status": "completed",
            "event_count": 42,
            "metadata": {"demo": True},
        })
        incident = IncidentRepository(db).add(
            incident_id=uuid.uuid4().hex[:12],
            title="Database persistence demo",
            severity="LOW",
            risk_score=25,
            session_id=session_id,
            target_id=target_id,
            anomaly_score=0.3,
            confidence=0.6,
            evidence={"demo": True},
        )
        DriftRepository(db).add(
            feature="event_rate",
            kind="numeric_mean_shift_z",
            score=1.2,
            severity="warning",
            baseline_version="demo-v1",
        )
        ModelSnapshotRepository(db).add(
            model_name="vantawave-demo",
            model_version="1",
            alias="champion",
            threshold=0.5,
            metrics={"f1": 0.85},
        )
        EvaluationRepository(db).add(
            model_name="vantawave-demo",
            dataset_name="demo",
            metrics={"f1": 0.85},
            recommendation="keep_current_model",
            reasons=["Demo metrics within policy."],
        )

        print("target:", orm_to_dict(target))
        print("session:", orm_to_dict(sensor_session))
        print("incident:", orm_to_dict(incident))

if __name__ == "__main__":
    main()
